## NUMPY

Numpy is fundamental to ML and DS.

It is a special type of array.

Basic list:

In [2]:
basic_list = [1, 3, 8, 7, 6, 5]
#To print list:
print(basic_list)
#To access items of list:
print(basic_list[2])

[1, 3, 8, 7, 6, 5]
8


It is problem in lists for large sets of data as lists have a different data types.

it is expensive computationally and costs a lot of money.

So, instead of using lists we can use numpy array for massive amounts of data.

Numpy array is just like a list but it's different.

In [3]:
#first step for using numpy is by importing the library as it doesn't come with python 
#Need to install it like: pip install numpy (in terminal)
import numpy as np


Numpy - Numeric Python

Anything in numpy array has to be of same data type like all numbers/boolean etc..

Datatype of numpy - ndarray

which means n-dimensional array.

### Creating numpy explicitly:

In [4]:
arr_exp = np.array([0, 3, 6, 9, 6, 1])
#np is alias name for numpy
print(arr_exp)

[0 3 6 9 6 1]


The output kind of looks like lists.

### To see shape of Array:

In [5]:
arr_exp.shape

(6,)

it is like len function. it gives the shape or number of elements in array.

### Creating numpy using arange:

Syntax:

arrayname = np.arange(stop)

Default:
start = 0
step = 1

In [6]:
arr_range = np.arange(9)
print(arr_range)

[0 1 2 3 4 5 6 7 8]


It prints all the elements till 9(excluding 9), default start is 0.

### Creating numpy using arange with step:

Syntax:

arrayname = np.arange(start, stop, step)

In [8]:
arr_ranstep = np.arange(5, 15, 3)
print(arr_ranstep)

[ 5  8 11 14]


### Creating numpy array of zeros:

Syntax:

arrayname = np.zeros(n)

default-0
n- number of elements

0. element of float type

In [9]:
arr_zero = np.zeros(7)
print(arr_zero)

[0. 0. 0. 0. 0. 0. 0.]


Till now we dealth with 1 - dimensional array.

Now, we deal with multi dimensional array. Numpy is great at multi-dimensional array.

### Using Full function:

Used for creating n dimensional array of all same value.

Syntax:

array_name = np.full((no. of elements), value of the element)

In [12]:
arr_full = np.full((13), 7)
print(arr_full)

[7 7 7 7 7 7 7 7 7 7 7 7 7]


## Creating Multi-dimensional Numpy array:

### Multi-dimensional array of zeros:

Syntax:

array_name = np.zeros((no. of dimensions, no. of elements in each dimension)

In [11]:
array_nzero = np.zeros((4, 8))
print(array_nzero)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


### Multi-dimensional array using Full:

Syntax:

array_name = np.full((no. of dimensions, no. of elements in each dimension), value of element)


In [14]:
array_nfull = np.full((4, 15), 9)
print(array_nfull)

[[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9 9 9 9 9 9 9 9 9]]


### Converting Python lists to np:

In [16]:
myList = [9, 6, 4, 3, 1, 2]
print(myList)
arr = np.array(myList)
print(arr)

[9, 6, 4, 3, 1, 2]
[9 6 4 3 1 2]


### Accessing Elements from Numpy array:

In [18]:
#Same as list accessment:
print(arr[4])

1
