In [1]:
import numpy as np

In [2]:
pos_arr = np.array([0,2,3,4,5,6,5,9,0,0,1])
all_arr = np.array([-7,-5,-2,0,0,1,2,6,8])

print(pos_arr)
print(all_arr)

[0 2 3 4 5 6 5 9 0 0 1]
[-7 -5 -2  0  0  1  2  6  8]


### Universal functions/ufunc:

functions do something to each element in our numpy array.

#### Finding square root of each element:

In [3]:
print(np.sqrt(pos_arr))
print(np.sqrt(all_arr)) #No sqrt possible for negative values

[0.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.23606798 3.         0.         0.         1.        ]
[       nan        nan        nan 0.         0.         1.
 1.41421356 2.44948974 2.82842712]


/var/folders/yc/xg70lc1d601f718q3_t6l2880000gq/T/ipykernel_10661/2685568630.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(all_arr))


#### Finding absolute value of function:

In [4]:
print(np.absolute(all_arr))

[7 5 2 0 0 1 2 6 8]


#### Finding exponents:

In [7]:
print(np.exp(pos_arr))
print(np.exp(all_arr))

[1.00000000e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.48413159e+02 8.10308393e+03
 1.00000000e+00 1.00000000e+00 2.71828183e+00]
[9.11881966e-04 6.73794700e-03 1.35335283e-01 1.00000000e+00
 1.00000000e+00 2.71828183e+00 7.38905610e+00 4.03428793e+02
 2.98095799e+03]


#### Finding Min/Max:

In [8]:
print(np.max(all_arr))
print(np.min(all_arr))

8
-7


#### Finding Sign: +ve/-ve

In [9]:
print(np.sign(all_arr))

[-1 -1 -1  0  0  1  1  1  1]


#### Trig Functions:

In [17]:
print(np.sin(pos_arr))
print(np.sin(all_arr))

[ 0.          0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
 -0.95892427  0.41211849  0.          0.          0.84147098]
[-0.6569866   0.95892427 -0.90929743  0.          0.          0.84147098
  0.90929743 -0.2794155   0.98935825]


In [18]:
print(np.tan(pos_arr))
print(np.tan(all_arr))

[ 0.         -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
 -3.38051501 -0.45231566  0.          0.          1.55740772]
[-0.87144798  3.38051501  2.18503986  0.          0.          1.55740772
 -2.18503986 -0.29100619 -6.79971146]


In [21]:
print(np.cos(pos_arr))
print(np.cos(all_arr))

[ 1.         -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.28366219 -0.91113026  1.          1.          0.54030231]
[ 0.75390225  0.28366219 -0.41614684  1.          1.          0.54030231
 -0.41614684  0.96017029 -0.14550003]


In [22]:
print(np.log(pos_arr))
print(np.log(all_arr))

[      -inf 0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.60943791 2.19722458       -inf       -inf 0.        ]
[       nan        nan        nan       -inf       -inf 0.
 0.69314718 1.79175947 2.07944154]


/var/folders/yc/xg70lc1d601f718q3_t6l2880000gq/T/ipykernel_10661/442442609.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(pos_arr))
/var/folders/yc/xg70lc1d601f718q3_t6l2880000gq/T/ipykernel_10661/442442609.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(all_arr))
/var/folders/yc/xg70lc1d601f718q3_t6l2880000gq/T/ipykernel_10661/442442609.py:2: RuntimeWarning: invalid value encountered in log
  print(np.log(all_arr))
