import numpy as np

In [30]:
#Creating basic numpy array:
np_arr = np.array([[1,2,3,4,5,6,7,8], [0,9,10,11,12,13,14,8], [1,5,9,0,4,6,7,5]])
oned_arr = np.array([1,2,3,4,5,6,7,8])
print(np_arr)
print(oned_arr)

[[ 1  2  3  4  5  6  7  8]
 [ 0  9 10 11 12 13 14  8]
 [ 1  5  9  0  4  6  7  5]]
[1 2 3 4 5 6 7 8]


### Basic Slicing:

Syntax:

array_name[no_of dimensions, no_of index]

no_of dimensions = :(default-all dimensions)

no_of index = elements slice mentioned = start:stop:step

step = 1 (default)

In [31]:
#for all dimensions:
print(np_arr[:,1:5])
#for 1 dimension:
print(oned_arr[1:5])

[[ 2  3  4  5]
 [ 9 10 11 12]
 [ 5  9  0  4]]
[2 3 4 5]


In [21]:
#for few dimensions:
print(np_arr[0:2,3:7])

[[ 4  5  6  7]
 [11 12 13 14]]


### Till the end of Array:

In [33]:
print(np_arr[:,2:])
#for 1 dimension:
print(oned_arr[2:])

[[ 3  4  5  6  7  8]
 [10 11 12 13 14  8]
 [ 9  0  4  6  7  5]]
[3 4 5 6 7 8]


In [22]:
print(np_arr[0:1,4:])

[[5 6 7 8]]


In [17]:
print(np_arr.shape)

(3, 8)


### Slicing using negative index:

In [34]:
print(np_arr[:,-6:-2])
#for 1 diemension:
print(oned_arr[-6:-2])

[[ 3  4  5  6]
 [10 11 12 13]
 [ 9  0  4  6]]
[3 4 5 6]


In [25]:
print(np_arr[1:2,-4:-1])

[[12 13 14]]


### Slicing using step:

In [35]:
print(np_arr[:,1:6:3])
#for 1 dimension:
print(oned_arr[1:6:3])

[[ 2  5]
 [ 9 12]
 [ 5  4]]
[2 5]


In [36]:
#slicing on entire array:
print(np_arr[:,::2])
#for 1 dimension:
print(oned_arr[::2])

[[ 1  3  5  7]
 [ 0 10 12 14]
 [ 1  9  4  7]]
[1 3 5 7]


### Pulling out from n-dimensional array:

Syntax:

array_name[dimension_number, index_number]

In [38]:
print(np_arr[2,6])

7


Syntax:

array_name[start_dimension:stop_dimension, start_index:stop_index])

In [39]:
#Slicing n-d array:
print(np_arr[1:,3:7])

[[11 12 13 14]
 [ 0  4  6  7]]


Note: Slicing doesn't change array